### ISSUE TITLE
‘Hello World’ Widget not working 

### ISSUE THREAD

**Issue by the-yaz** [annotorious/annotorious#311]
I want to customize the widget and i start by reading the documentation specially the [‘Hello World’ Widget](https://annotorious.github.io/guides/editor-widgets/) , I tried to follow the documentation but I probably didn't understand it well , first i created a file with name "color-selector-widget.js" and paste to it "`var ColorSelectorWidget = function(args) { //rest of code }`" and then i created another file with name "color-formatter.js" and past to it the formater code `var ColorFormatter = function (annotation) { //rest of code }` and add scripts to the index.html and past the widget init to it , but unfortunately the annotorious stop working , what did i do wrong ? (Note : My main goal is to customize the widget by removing the comment and tag sections and replace them by an select options element and I'm starting from this documentation).
here is my index code : 
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="annotorious.min.css">
        <link rel="stylesheet" href="style.css">
      </head>
      
      <body>
        <div id="content">
          <img id="hallstatt" src="640px-Hallstatt.jpg">
        </div>
      
        <script type="text/javascript" src="annotorious.min.js"></script>
        <script type="text/javascript" src="annotorious.umd.js.map"></script>
        <script type="text/javascript" src="recogito-polyfills.js"></script>
        <script type="text/javascript" src="separate.js"></script>
        <script src="color-selector-widget.js"></script>
        <script src="color-formatter.js"></script>
 
     <script>
          (function() {
            
            var anno = Annotorious.init({
              image: 'hallstatt',
              widgets: [
                ColorSelectorWidget,
                'COMMENT',
                'TAG'
              ],
              formatter: ColorFormatter
            });

           console.log("show from index html")
      
            anno.on('createAnnotation', function(annotation) {
              // Do something
            });
          })()
        </script>
      
      </body>
</html>
```

**Comment by rsimon** [comment]
This sounds as if you are simply adding two new source files, with locally declared variables. ColorFormatter and ColorSelectorWidget might not be visible to the main script. You could try declaring both in the main file, just to be sure, and see whether the browser console (F12 key on Chrome and Firefox) shows any error messages?

**Comment by the-yaz** [comment]
thank you for your reply , i tried what you say , i add the local variables to the script element in the index.html not a good practice but i guess it's better , now i can select the zone but the problem is the widget does not show up anymore and the button are being added to the body (under the image ) and i got this error in the console : "```

> Uncaught (in promise) TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
>     at Pc.renderWidget (index.jsx:283:53)
>     at Pc.componentDidMount (index.jsx:283:53)
>     at index.jsx:283:53
>     at Array.some (<anonymous>)
>     at index.jsx:283:53
>     at Array.some (<anonymous>)
>     at Ri (index.jsx:283:53)
>     at index.jsx:283:53
>     at Array.some (<anonymous>)
>     at dn (index.jsx:283:53)

 .

  here is a here is my index : 
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="annotorious.min.css">
        <link rel="stylesheet" href="style.css">
      </head>
      
      <body>
        <div id="content">
          <img id="hallstatt" src="640px-Hallstatt.jpg">
        </div>
      
        <script type="text/javascript" src="annotorious.min.js"></script>
       
        <script type="text/javascript" src="recogito-polyfills.js"></script>
        <script type="text/javascript" src="separate.js"></script>
       
 
     <script>
          (
            
          function () {
              var ColorSelectorWidget = function (args) {

                // 1. Find a current color setting in the annotation, if any
                var currentColorBody = args.annotation ?
                  args.annotation.bodies.find(function (b) {
                    return b.purpose == 'highlighting';
                  }) : null;

                // 2. Keep the value in a variable
                var currentColorValue = currentColorBody ? currentColorBody.value : null;

                // 3. Triggers callbacks on user action
                var addTag = function (evt) {
                  if (currentColorBody) {
                    args.onUpdateBody(currentColorBody, {
                      type: 'TextualBody',
                      purpose: 'highlighting',
                      value: evt.target.dataset.tag
                    });
                  } else {
                    args.onAppendBody({
                      type: 'TextualBody',
                      purpose: 'highlighting',
                      value: evt.target.dataset.tag
                    });
                  }
                }

                // 4. This part renders the UI elements
                var createButton = function (value) {
                  var button = document.createElement('button');

                  if (value == currentColorValue)
                    button.className = 'selected';

                  button.dataset.tag = value;
                  button.style.backgroundColor = value;
                  button.addEventListener('click', addTag);
                  return button;
                }
                var container = document.createElement('div');
                container.className = 'colorselector-widget';

                var button1 = createButton('RED');
                var button2 = createButton('GREEN');
                var button3 = createButton('BLUE');

                container.appendChild(button1);
                container.appendChild(button2);
                container.appendChild(button3);

                // Find the target element with the ID "content" and append the container to it
                var contentElement = document.getElementById('content');
                if (contentElement) {
                  contentElement.appendChild(container);
                }

              }
              var ColorFormatter = function (annotation) {
                var highlightBody = annotation.bodies.find(function (b) {
                  return b.purpose === 'highlighting';
                });

                if (highlightBody) return highlightBody.value;


              };

              var anno = Annotorious.init({
                image: 'hallstatt',
                widgets: [
                  
                  'COMMENT',
                  'TAG',
                  ColorSelectorWidget
                ],
                formatter: ColorFormatter
              });

              console.log("show from index html")

              anno.on('createAnnotation', function (annotation) {
                // Do something
              });
            })()
        </script>
      
      </body>
</html>
```

**Comment by rsimon** [comment]
Hi,

you're not returning a value from your `ColorSelectorWiget` function. The last line should be `return container;`. (See [docs](https://annotorious.github.io/guides/editor-widgets/)).

> not a good practice but i guess it's better 

Obviously, you'll want to split your project into different source files. But then you also need to make sure that you're properly exposing your functions to the rest of the script, e.g. via modules. Otherwise, you'd need to go for global variables, speaking of not good practices ;-)

**Comment by the-yaz** [comment]
thank you so much for your support
