### ISSUE TITLE
NPM install 404 error

### ISSUE THREAD

**Issue by Shavindra** [annotorious/annotorious#47]
```

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'i',
1 verbose cli   '@recogito/annotorious'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.0.0
4 verbose npm-session a855050a092fed1a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@recogito%2fannotorious 731ms
8 http fetch GET 404 https://registry.npmjs.org/@recogito%2fannotorious 140ms
9 silly fetchPackageMetaData error for @recogito/annotorious@latest 404 Not Found - GET https://registry.npmjs.org/@recogito%2fannotorious - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 19512ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@recogito%2fannotorious - Not found
12 verbose stack     at C:\nvm\v12.0.0\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:88:5)
13 verbose statusCode 404
14 verbose pkgid @recogito/annotorious@latest
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@recogito/annotorious"
18 verbose node v12.0.0
19 verbose npm  v6.9.0
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@recogito%2fannotorious - Not found
22 error 404
23 error 404 '@recogito/annotorious@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

```

**Comment by rsimon** [comment]
Hi,

hm - that's weird. Might be a temporary problem with the NPM registry. I'll check back later and see if the problem persists. If it does, I'll try publishing a new version... thanks for letting me know!

**Comment by rsimon** [comment]
Hi again,

I tried again just now and it worked for me this time. Can you check once more?

**Comment by Shavindra** [comment]
hmmm that's strange... for me still the same 

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@recogito%2fannotorious - Not found
npm ERR! 404
npm ERR! 404  '@recogito/annotorious@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```


```

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@recogito%2fannotorious - Not found
npm ERR! 404
npm ERR! 404  '@recogito/annotorious@2.0.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

**Comment by rsimon** [comment]
Can you post the OS and node/npm versions you are using?

**Comment by rsimon** [comment]
I just got this working on Linux (Ubuntu), using node v14.5.0 and npm 6.14.5

```
$ npm install --save @recogito/annotorious
npm WARN timeago-react@3.0.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN downshift@5.4.7 requires a peer of react@>=16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.1 requires a peer of react@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.1 requires a peer of react-dom@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-contenteditable@3.3.5 requires a peer of react@>=16.3 but none is installed. You must install peer dependencies yourself.
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

+ @recogito/annotorious@2.0.5
updated 1 package and audited 43 packages in 2.935s
found 0 vulnerabilities
```

**Comment by Shavindra** [comment]
![image](https://user-images.githubusercontent.com/1387263/89521359-a4c0d080-d7df-11ea-9294-868304737d14.png)

^^
could be registry issue?


Node: v12.0.0
NPM: 6.9.0
Windows 10

**Comment by rsimon** [comment]
Ok, those node/npm versions definitely look ok. Weird - I can open <https://registry.npmjs.org/@recogito/annotorious> on my end of the world (Austria) just fine. 

Puzzled... I can only guess that it might indeed be some temporary network problems on the side of the registry and its mirrors.

**Comment by Shavindra** [comment]
Seems so it's working now :)
